/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaEntidades.Gasto;
import CapaEntidades.Moneda;
import CapaEntidades.TipoDocumento;
import CapaNegocio.GastoBL;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmGastos extends javax.swing.JFrame {
    
    private String perfilUsuario;

    public FrmGastos(String perfil) {
        initComponents();
        this.perfilUsuario = perfil;
        setLocationRelativeTo(null);
        setResizable(false);        
        listar();
        cargartipodocumento();
        cargarmoneda();
        txtId.setVisible(true);
    }
    
    public FrmGastos() {
        this("Operador");
    }

    GastoBL oGastoBL = new GastoBL();

    void listar() {
        DefaultTableModel model = new DefaultTableModel();
        String[] titulos = {"Fecha Gasto", "Tipo Documento", "Numero Documento", "Concepto", "Proveedor", "TipoMoneda", "Importe"};
        model.setColumnIdentifiers(titulos);

        List<Gasto> lista = oGastoBL.listarGasto();
        System.out.println("Cantidad de gastos: " + lista.size());

        for (Gasto ogasto : lista) {
            Object data[] = {
                ogasto.getFechaGasto(),
                ogasto.getTipoDoc(),
                ogasto.getNumDoc(),
                ogasto.getProveedor(),
                ogasto.getConcepto(),
                ogasto.getTipoMoneda(),
                ogasto.getImporte()};

            model.addRow(data);
        }
        tblGastos.setModel(model);
    }

    void cargartipodocumento() {
        cboTipo.removeAllItems();
        List<TipoDocumento> documento = new ArrayList();
        documento = oGastoBL.listarDocumento();
        for (TipoDocumento otipodocumento : documento) {
            cboTipo.addItem(otipodocumento.getTipoDocumento());
        }
    }

    void cargarmoneda() {
        cboMoneda.removeAllItems();
        List<Moneda> moneda = new ArrayList();
        moneda = oGastoBL.listarMoneda();
        for (Moneda omoneda : moneda) {
            cboMoneda.addItem(omoneda.getMoneda());
        }
    }

    void limpiar() {
        txtFecha.setText("");
        txtDocumento.setText("");
        txtProveedor.setText("");
        txtConcepto.setText("");
        txtImporte.setText("");
        cboTipo.removeAllItems();
        cboMoneda.removeAllItems();
        cargartipodocumento();
        cargarmoneda();
    }

    void activarbotones(boolean botonGuardar, boolean botonBuscar, boolean botonEliminar) {

        btnGuardar.setEnabled(botonGuardar);
        btnBuscar.setEnabled(botonBuscar);
        btnEliminar.setEnabled(botonEliminar);
    }

    void mensaje(String men) {
        JOptionPane.showMessageDialog(this, men, "Aviso", 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboMoneda = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Fecha");

        jLabel5.setText("Importe");

        jLabel3.setText("N. Documento");

        jLabel4.setText("Proveedor");

        jLabel6.setText("Tipo documento");

        cboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoActionPerformed(evt);
            }
        });

        jLabel7.setText("Concepto");

        jLabel8.setText("Tipo Moneda");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Registro Gastos");

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGastos);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Añadir.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Guardar.png"))); // NOI18N
        btnGuardar.setText("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Actualizar.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecha)
                            .addComponent(txtDocumento)
                            .addComponent(txtProveedor)
                            .addComponent(txtConcepto)
                            .addComponent(cboMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(66, 66, 66)
                        .addComponent(btnGuardar)
                        .addGap(57, 57, 57)
                        .addComponent(btnBuscar)
                        .addGap(76, 76, 76)
                        .addComponent(btnEliminar)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnBuscar)
                            .addComponent(btnGuardar)
                            .addComponent(btnEliminar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
        txtFecha.requestFocus();

        if (btnNuevo.getText().equalsIgnoreCase("Nuevo")) {
            btnNuevo.setText("Cancelar");
            limpiar();
            activarbotones(true, false, false);
        } else {
            btnNuevo.setText("Nuevo");
            limpiar();
            activarbotones(false, true, false);
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");

        try {
            if (txtDocumento.getText().isEmpty() || txtProveedor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El num de Documento y la Razon social son obligatorios");
                return;
            } else {
                GastoBL oGastoBL = new GastoBL();
                int g;
                String usuarioActual = FrmLogin.usuarioActual;
                Date fechaActual = new Date(System.currentTimeMillis());
                System.out.println("Iniciando el proceso de guardado...");
                
                if (!oGastoBL.validarRazonSocial(txtProveedor.getText())) {
                    int RSocial = JOptionPane.showConfirmDialog(this, "El proveedor no existe. ¿Desea agregar proveedor?", 
                            "Proveedor no encontrado", JOptionPane.YES_NO_OPTION);
                    if (RSocial == JOptionPane.YES_NO_OPTION) {
                        FrmProveedor frmProveedor = new FrmProveedor();
                        frmProveedor.setVisible(true);
                    }
                    return;
                }

                if (txtId.getText().length() == 0) {

                    g = oGastoBL.agregarGasto(new Gasto(
                            txtFecha.getText(),
                            cboTipo.getSelectedItem().toString(),
                            txtDocumento.getText(),
                            txtProveedor.getText(),
                            txtConcepto.getText(),                            
                            cboMoneda.getSelectedItem().toString(),
                            Double.parseDouble(txtImporte.getText()),
                            fechaActual,
                            usuarioActual
                    ));
                    System.out.println("Gasto agregado, resultado; " + g);
                } else {
                    System.out.println("Proveedor: " + txtProveedor.getText());
                    g = oGastoBL.actualizarGasto(new Gasto(
                            Integer.parseInt(txtId.getText()),
                            txtFecha.getText(),
                            cboTipo.getSelectedItem().toString(),
                            txtDocumento.getText(),
                            txtProveedor.getText(),
                            txtConcepto.getText(),                            
                            cboMoneda.getSelectedItem().toString(),
                            Double.parseDouble(txtImporte.getText()),
                            fechaActual,
                            usuarioActual));
                    System.out.println("Gasto actualizado, resultado: " + g);
                }
            }
        } catch (Exception e) {            
            mensaje(e.getMessage());
        }
        activarbotones(false, true, false);
        btnNuevo.setText("NUEVO");
        listar();
        cargartipodocumento();
        cargarmoneda();
        limpiar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        int me = JOptionPane.showConfirmDialog(null, "Está Seguro?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (me == JOptionPane.YES_OPTION) {            
            String NroDocumento = txtDocumento.getText();
            
            int gastoEliminado = oGastoBL.eliminarGasto(NroDocumento); 
            
            if (gastoEliminado==1) {
                JOptionPane.showMessageDialog(this, "Gasto eliminado");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el gasto. Verificar Nro Documento");
            }            
        } else {
            JOptionPane.showMessageDialog(this, "No se eliminó");            
        }
        activarbotones(false, true, true);
        listar();
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
        String numeroDocumento = JOptionPane.showInputDialog("Ingrese el número de documento a buscar");

        if (numeroDocumento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese número de documento");
        } else {
            Gasto ogasto = oGastoBL.buscarGasto(numeroDocumento);
            if (ogasto == null) {
                JOptionPane.showMessageDialog(this, "Gasto no existe");
            } else {
                txtId.setText(String.valueOf(ogasto.getIdGasto()));
                txtFecha.setText(String.valueOf(ogasto.getFechaGasto()));
                cboTipo.setSelectedItem(ogasto.getTipoDoc());
                txtDocumento.setText(ogasto.getNumDoc());
                txtConcepto.setText(ogasto.getConcepto());
                txtProveedor.setText(ogasto.getProveedor());
                cboMoneda.setSelectedItem(ogasto.getTipoMoneda());
                txtImporte.setText("" + ogasto.getImporte());
            }
        }        
        activarbotones(true, true, true);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmPrincipal frmPrincipal = new FrmPrincipal(perfilUsuario);
        frmPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboMoneda;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtProveedor;
    // End of variables declaration//GEN-END:variables
}
