/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

/**
 *
 * @author yenko
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private String perfilUsuario;

    public FrmPrincipal(String perfil) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.perfilUsuario = perfil;
        configurarMenuPerfil();
    }

    private void configurarMenuPerfil() {
        if ("operador".equalsIgnoreCase(perfilUsuario)) {
            MUsuario.setVisible(false);
        } else {
            MUsuario.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MFile = new javax.swing.JMenu();
        OpClose = new javax.swing.JMenuItem();
        MUsuario = new javax.swing.JMenu();
        OpAdminUsuario = new javax.swing.JMenuItem();
        MProveedor = new javax.swing.JMenu();
        OpAdminProveedores = new javax.swing.JMenuItem();
        MGastos = new javax.swing.JMenu();
        OpAdminGastos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        OpConsProve = new javax.swing.JMenuItem();
        OpConsGastos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondo.jpg"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        MFile.setText("File");

        OpClose.setText("Close");
        OpClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpCloseActionPerformed(evt);
            }
        });
        MFile.add(OpClose);

        jMenuBar1.add(MFile);

        MUsuario.setText("Usuario");

        OpAdminUsuario.setText("Administrar Usuario");
        OpAdminUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpAdminUsuarioActionPerformed(evt);
            }
        });
        MUsuario.add(OpAdminUsuario);

        jMenuBar1.add(MUsuario);

        MProveedor.setText("Proveedor");

        OpAdminProveedores.setText("Administrar Proveedores");
        OpAdminProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpAdminProveedoresActionPerformed(evt);
            }
        });
        MProveedor.add(OpAdminProveedores);

        jMenuBar1.add(MProveedor);

        MGastos.setText("Gastos");

        OpAdminGastos.setText("Administrar Gastos");
        OpAdminGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpAdminGastosActionPerformed(evt);
            }
        });
        MGastos.add(OpAdminGastos);

        jMenuBar1.add(MGastos);

        jMenu2.setText("Consultas");

        OpConsProve.setText("Consulta Proveedor");
        OpConsProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpConsProveActionPerformed(evt);
            }
        });
        jMenu2.add(OpConsProve);

        OpConsGastos.setText("Consulta Gastos");
        jMenu2.add(OpConsGastos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_OpCloseActionPerformed

    private void OpAdminUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpAdminUsuarioActionPerformed
        // TODO add your handling code here:        
        FrmUsuario us = new FrmUsuario();
        us.setVisible(true);
    }//GEN-LAST:event_OpAdminUsuarioActionPerformed

    private void OpAdminProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpAdminProveedoresActionPerformed
        // TODO add your handling code here:
        FrmProveedor pr = new FrmProveedor(perfilUsuario);
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OpAdminProveedoresActionPerformed

    private void OpAdminGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpAdminGastosActionPerformed
        // TODO add your handling code here:
        FrmGastos gas = new FrmGastos();
        gas.setVisible(true);
    }//GEN-LAST:event_OpAdminGastosActionPerformed

    private void OpConsProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpConsProveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpConsProveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal("Administrador").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MFile;
    private javax.swing.JMenu MGastos;
    private javax.swing.JMenu MProveedor;
    private javax.swing.JMenu MUsuario;
    private javax.swing.JMenuItem OpAdminGastos;
    private javax.swing.JMenuItem OpAdminProveedores;
    private javax.swing.JMenuItem OpAdminUsuario;
    private javax.swing.JMenuItem OpClose;
    private javax.swing.JMenuItem OpConsGastos;
    private javax.swing.JMenuItem OpConsProve;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
